### ISSUE TITLE
Website not commited to gh-pages branch

### ISSUE THREAD

**Issue by juliohm** [MichaelHatherly/Documenter.jl#38]
Hi,

Could you please help me debug this example? https://github.com/juliohm/ImageQuilting.jl

I didn't create a personal access token on GitHub, is it required for the automatic commit on `gh-pages`?

**Comment by MichaelHatherly** [comment]
Yes, an access token is needed when using `deploydocs` on travis. It is possible to just build and deploy locally by installing mkdocs and pushing to the `gh-pages` branch directly, but of course that won't be automatic.

Other than the token, you'll need to set `julia =  "release"` rather than `julia = "0.4"` in `deploydocs` so that it matches the value in `.travias.yml`.

**Comment by juliohm** [comment]
@MichaelHatherly I just added the token to Travis and corrected the `julia = release` as you suggested. Now I see the `latest` directory in the `gh-pages` branch on GitHub. How much time it takes for GitHub to generate the website? I cannot see the results in https://juliohm.github.io/ImageQuiltilng.jl/latest

I also would like to check the docs locally sometimes, I tried running `julia make.jl` and `mkdocs serve` in the `docs/` directory, but I am getting a 404 error webpage. Do you know what can be causing the issue?

**Comment by MichaelHatherly** [comment]
> How much time it takes for GitHub to generate the website?

Typically it takes a few minutes to become available. It's here now http://juliohm.github.io/ImageQuilting.jl/latest/home/

Note the `home/` since you're using `home.md` rather than the usual `index.md` for the main page.

> I also would like to check the docs locally sometimes

Same thing applies here with the need to use the `home/` url (`http://localhost:8000/home/`) instead of the standard one. `mkdocs serve` is returning the correct page for me locally with your package.

**Comment by juliohm** [comment]
That is awesome! I renamed `home.md` to `index.md` and everything is working just fine. Thank you for this very cool package!

**Comment by MichaelHatherly** [comment]
Great, glad it's working now!
